[versions]
activityCompose = "1.12.2"
agp = "8.13.2"
androidJunit = "1.3.0"
appcompat = "1.7.1"
composeBom = "2026.01.00"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
jetbrainsKotlinJvm = "2.3.0"
junit = "4.13.2"
junitBom = "6.0.2"
kotlin = "2.3.0"
lifecycleRuntimeKtx = "2.10.0"
mockkVersion = "1.14.7"
material = "1.13.0"
navigationCompose = "2.9.6"
robolectric-core = "4.16.1"
screenshot = "0.0.1-alpha13"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material-extended-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-googlefonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
io-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
io-mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockkVersion" }
io-mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockkVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-param = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
robolectric-core = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric-core" }
screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshot" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }
# custom plugins
# Add your custom convention plugins here at the end
fairshare-android-application = { id = "fairshare.android.application" }
fairshare-android-library = { id = "fairshare.android.library" }
fairshare-android-common = { id = "fairshare.android.common" }
